services:
  # Redis cache service
  redis:
    image: redis:7-alpine
    container_name: word_count_redis
    ports:
      - "6379:6379"
    networks:
      - word_count_network

  # Server 1
  server1:
    build: .
    container_name: word_count_server1
    hostname: server1
    volumes:
      - ./server:/app/server
      - ./texts:/app/texts
    command: python /app/server/server.py
    environment:
      - SERVER_NAME=server1
      - SERVER_PORT=18861
    expose:
      - "18861"
    depends_on:
      - redis
    networks:
      - word_count_network

  # Server 2
  server2:
    build: .
    container_name: word_count_server2
    hostname: server2
    volumes:
      - ./server:/app/server
      - ./texts:/app/texts
    command: python /app/server/server.py
    environment:
      - SERVER_NAME=server2
      - SERVER_PORT=18861
    expose:
      - "18861"
    depends_on:
      - redis
    networks:
      - word_count_network

  # Server 3
  server3:
    build: .
    container_name: word_count_server3
    hostname: server3
    volumes:
      - ./server:/app/server
      - ./texts:/app/texts
    command: python /app/server/server.py
    environment:
      - SERVER_NAME=server3
      - SERVER_PORT=18861
    expose:
      - "18861"
    depends_on:
      - redis
    networks:
      - word_count_network

  # Load Balancer
  load_balancer:
    build: .
    container_name: word_count_lb
    volumes:
      - ./load_balancer:/app/load_balancer
    command: python -u /app/load_balancer/load_balancer.py
    ports:
      - "18860:18860"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - word_count_network
    environment:
      - LB_ALGORITHM=least_connections
      - PYTHONUNBUFFERED=1

  # Client 1
  client1:
    build: .
    container_name: word_count_client1
    hostname: client1
    volumes:
      - ./client:/app/client
    command: sleep infinity
    depends_on:
      - load_balancer
    networks:
      - word_count_network
    environment:
      - CLIENT_ID=1
    stdin_open: true
    tty: true

  # Client 2
  client2:
    build: .
    container_name: word_count_client2
    hostname: client2
    volumes:
      - ./client:/app/client
    command: sleep infinity
    depends_on:
      - load_balancer
    networks:
      - word_count_network
    environment:
      - CLIENT_ID=2
    stdin_open: true
    tty: true

  # Client 3
  client3:
    build: .
    container_name: word_count_client3
    hostname: client3
    volumes:
      - ./client:/app/client
    command: sleep infinity
    depends_on:
      - load_balancer
    networks:
      - word_count_network
    environment:
      - CLIENT_ID=3
    stdin_open: true
    tty: true

  # Client 4
  client4:
    build: .
    container_name: word_count_client4
    hostname: client4
    volumes:
      - ./client:/app/client
    command: sleep infinity
    depends_on:
      - load_balancer
    networks:
      - word_count_network
    environment:
      - CLIENT_ID=4
    stdin_open: true
    tty: true

  # Client 5
  client5:
    build: .
    container_name: word_count_client5
    hostname: client5
    volumes:
      - ./client:/app/client
    command: sleep infinity
    depends_on:
      - load_balancer
    networks:
      - word_count_network
    environment:
      - CLIENT_ID=5
    stdin_open: true
    tty: true

networks:
  word_count_network:
    driver: bridge